const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=fs.readFileSync('web/app.js','utf8');
const code=source.slice(source.indexOf('function safeLink('),source.indexOf('function renderDetail('));
const context={URL,escape:s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};
vm.createContext(context);vm.runInContext(code,context);
const m={id:'fixture',content:{media:[{status:'saved',path:'capture/images/a.png'}]}};
const result=context.richContent('前文\n![图解](capture/images/a.png)\n后文<script>unsafe()</script>',m);
assert(result.indexOf('前文')<result.indexOf('<figure'));
assert(result.indexOf('</figure>')<result.indexOf('后文'));
assert(result.includes('src="/api/materials/fixture/images/capture/images/a.png"'));
assert(result.includes('&lt;script&gt;')&&!result.includes('<script>'));
assert.equal(context.safeLink('javascript:alert(1)'),'#');
assert(!context.richContent('![远程图](https://example.org/a.png)',m).includes('<img'));
assert(!context.richContent('![逃逸](../../credentials/x.json)',m).includes('<img'));
const groupMaterial={id:'fixture',content:{media:[{status:'saved',path:'images/a.png'},{status:'saved',path:'images/b.png'}]}};
const gallery=context.richContent('前文\n![帖子图片](images/a.png)\n\n![录音室的控制台](images/b.png)\n后文',groupMaterial);
assert(gallery.includes('data-image-count="2"'));
assert(gallery.includes('alt="帖子图片"')&&!gallery.includes('<figcaption>帖子图片</figcaption>'));
assert(gallery.includes('<figcaption>录音室的控制台</figcaption>'));
assert(gallery.indexOf('images/a.png')<gallery.indexOf('images/b.png'));
const separated=context.richContent('![图片](images/a.png)\n\n这段文字在两张图之间\n\n![图解](images/b.png)',groupMaterial);
assert.equal((separated.match(/data-image-count="1"/g)||[]).length,2);
assert(separated.indexOf('</figure>')<separated.indexOf('这段文字'));
assert(separated.indexOf('这段文字')<separated.lastIndexOf('<figure'));
assert.equal(context.imageCaption('帖子图片 2'),'');
assert.equal(context.imageCaption('不同年份的录音室照片'),'不同年份的录音室照片');
console.log('Reader checks passed: image order, local route, HTML escaping, URL safety, remote/path protection');

context.bilingualVisible=true;
m.reader_translation={units:{'body:0':{text:'Translated <script>unsafe()</script>',language:'zh',source:'本机机器翻译'},'body:1':{text:'第二段译文',language:'zh',source:'本机机器翻译'}}};
const bilingualHtml=context.richContent('First.\n![image](capture/images/a.png)\n\nSecond.',m);
assert(bilingualHtml.indexOf('Translated')<bilingualHtml.indexOf('<figure'));
assert(bilingualHtml.indexOf('</figure>')<bilingualHtml.indexOf('第二段译文'));
assert(bilingualHtml.includes('&lt;script&gt;')&&!bilingualHtml.includes('<script>'));
context.bilingualVisible=false;
assert(!context.richContent('First.',m).includes('Translated'));
console.log('Bilingual original order, escaping and visibility checks passed');

async function checkBilingualSwitch(){
  const elements={};
  for(const key of ['#bilingualToggle','#retryTranslation','#bilingualStatus','#transcriptSection','#videoWorkbench','#originalSection .prose','#commentsBody','#notesText','#platformPlayer'])elements[key]={hidden:false,innerHTML:'',attributes:{},setAttribute(k,v){this.attributes[k]=v;}};
  elements['#notesText'].value='未保存的理解草稿';elements['#platformPlayer'].currentTime=64.42;elements['#platformPlayer'].src='unchanged-player';
  const originalPlayer=elements['#platformPlayer'];let rendered=0,apiCalls=0;
  const switchMaterial={id:'fixture',url:'https://example.org/source',body:'First.',notes:'已保存理解',revision:1,content:{segments:[{start:0,end:2,text:'First.'}],comments:[{body:'A useful reply.',author:'Reader'}],comments_status:'一条已存档回复'},reader_translation:{complete:true,units:{'body:0':{text:'第一段译文',language:'zh',source:'本机机器翻译'},'comment:0:0':{text:'回复译文',language:'zh',source:'本机机器翻译'}}}};
  Object.assign(context,{$:key=>elements[key]||null,guard:fn=>fn,icon:()=>'',current:switchMaterial,captionList:{anchor:()=>({sourceIndex:450,offset:12})},translationRequests:new Set(),localStorage:{setItem(){}},renderVideoTranscript:(item,anchor)=>{assert.equal(anchor.sourceIndex,450);rendered++;},api:async()=>{apiCalls++;return {job_id:'fixture-job'};}});
  vm.runInContext(source.slice(source.indexOf('function bilingualSwitch('),source.indexOf('function renderVideoTranscript(')),context);
  context.bilingualVisible=false;context.bindBilingual(switchMaterial);
  await elements['#bilingualToggle'].onclick();
  assert.equal(elements['#bilingualToggle'].attributes['aria-checked'],'true');assert(elements['#commentsBody'].innerHTML.includes('回复译文'));assert(elements['#originalSection .prose'].innerHTML.includes('第一段译文'));
  await elements['#bilingualToggle'].onclick();
  assert.equal(elements['#bilingualToggle'].attributes['aria-checked'],'false');assert(!elements['#commentsBody'].innerHTML.includes('回复译文'));assert(!elements['#originalSection .prose'].innerHTML.includes('第一段译文'));
  context.acceptTranslation({...switchMaterial,revision:7,events:[]});assert.equal(context.current.revision,7);
  assert.equal(elements['#notesText'].value,'未保存的理解草稿');assert.equal(elements['#platformPlayer'],originalPlayer);assert.equal(originalPlayer.currentTime,64.42);assert.equal(originalPlayer.src,'unchanged-player');assert.equal(apiCalls,0);assert.equal(rendered,3);
  switchMaterial.reader_translation=null;switchMaterial.translation_job=null;
  await elements['#bilingualToggle'].onclick();assert.equal(apiCalls,1);
  await elements['#bilingualToggle'].onclick();await elements['#bilingualToggle'].onclick();assert.equal(apiCalls,1);
  assert.equal(elements['#notesText'].value,'未保存的理解草稿');assert.equal(originalPlayer.currentTime,64.42);
  console.log('Bilingual switch covers body and replies, preserves player/draft/anchor and deduplicates queued translation');
}
checkBilingualSwitch().catch(error=>{console.error(error);process.exitCode=1;});
